In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("./solicitacoescredito.csv")

df.head(10)

,numero_solicitacao,razaoSocial,nomeFantasia,cnpjSemTraco,maiorAtraso,margemBrutaAcumulada,percentualProtestos,primeiraCompra,prazoMedioRecebimentoVendas,titulosEmAberto,...,periodoDemonstrativoEmMeses,custos,anoFundacao,intervaloFundacao,capitalSocial,restricoes,empresa_MeEppMei,scorePontualidade,limiteEmpresaAnaliseCredito,dataAprovadoNivelAnalista
0,1,James Richardson-Patel,Alexandra Williams,KEBE17609492220843,0,0.252448,0.0,2015-12-10T00:00:00,0,0.00,...,12.0,0.0,2003.0,Acima de 17 anos,90000.0,False,True,1.00000,43200.0,2020-02-03T20:57:33
1,2,Dr. Geoffrey Walsh,Mr. Darren Arnold,JRBK88908250677300,0,0.000000,NaN,2019-06-12T17:28:31,0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN
2,3,Joanna Hudson,Dr. David Rees,GCVQ28531614261293,4,0.624777,0.0,2019-11-27T00:00:00,0,0.00,...,7.0,0.0,2014.0,De 6 a 10 anos,20000.0,False,True,1.00000,4320.0,2020-02-04T16:40:49
3,4,Gordon Jones-Hopkins,Sara Reid-Robson,KJND32266018316396,20,0.000000,NaN,2017-02-13T17:20:27,0,0.00,...,12.0,0.0,2013.0,De 6 a 10 anos,30000.0,False,True,0.00000,5920.0,2020-02-04T16:37:52
4,5,Nigel Lee,Dr. Stanley Duncan,CGQN15826802440348,20,0.454088,0.0,2010-07-13T00:00:00,20,1486.95,...,9.0,40680051.0,2002.0,Acima de 17 anos,75000.0,False,False,1.00000,89000.0,2020-02-04T15:06:28
5,6,Liam Jackson,Gerard Gordon,KAYS53232027306925,0,0.000000,NaN,2019-06-28T10:25:57,0,0.00,...,12.0,0.0,2011.0,De 6 a 10 anos,15000.0,False,True,0.00000,38400.0,2020-02-04T15:10:46
6,7,Alexander Baker-Wells,Dr. Caroline Ali,PYOL43118620147076,16,0.000000,NaN,2011-03-02T11:27:13,0,0.00,...,12.0,156394112.0,1982.0,Acima de 17 anos,30515674.0,True,False,0.00000,18132588.0,2020-02-05T14:31:22
7,8,Jean Berry,Gregory Gould,NLUX93496216176463,4,0.350175,0.0,2007-07-02T00:00:00,102,208980.00,...,9.0,0.0,2000.0,Acima de 17 anos,120000.0,False,False,1.00000,768233.0,2020-02-05T20:05:40
8,9,Elliot Stephenson,Adrian Graham,LOVL82962402474134,43,0.245818,0.0,2006-07-10T00:00:00,27,6432.00,...,12.0,-49267738.0,2000.0,Acima de 17 anos,1000000.0,False,False,1.00000,6910219.0,2020-02-05T20:07:07
9,10,Dr. Dale Dawson,Caroline Hale,NXKJ36775578171965,24,0.000012,0.0,2011-02-24T00:00:00,0,22733.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.83159,NaN,NaN

In [5]:
df.maiorAtraso.mean()

24.642594450016716